// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadVideo(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadVideo'](arg1, arg2, arg3);
}

export function GetDefaultSavePath() {
  return window['go']['main']['App']['GetDefaultSavePath']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function SelectSavePath() {
  return window['go']['main']['App']['SelectSavePath']();
}

export function SetupLinuxDependencies() {
  return window['go']['main']['App']['SetupLinuxDependencies']();
}

export function SetupWindowsDependencies() {
  return window['go']['main']['App']['SetupWindowsDependencies']();
}

export function UpdateYtdlp() {
  return window['go']['main']['App']['UpdateYtdlp']();
}
