// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload():Promise<void>;

export function CheckDependencies():Promise<main.DependencyStatus>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadGenericVideo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadVideo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetDefaultSavePath():Promise<string>;

export function GetGenericVideoInfo(arg1:string):Promise<string>;

export function GetVideoInfo(arg1:string):Promise<string>;

export function IsAppReady():Promise<boolean>;

export function NotifyDownloadComplete(arg1:string,arg2:string):Promise<void>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function SelectSavePath(arg1:string):Promise<string>;

export function SetupLinuxDependencies():Promise<void>;

export function SetupWindowsDependencies():Promise<void>;

export function UpdateYtdlp():Promise<void>;
